// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBis_wXp1WCY6bHnJgUi0aqqkWqb5MO-LE',
    appId: '1:841446464080:web:ea090612f5e5fd31ba4f55',
    messagingSenderId: '841446464080',
    projectId: 'my-firebase-app-mad-23a22',
    authDomain: 'my-firebase-app-mad-23a22.firebaseapp.com',
    storageBucket: 'my-firebase-app-mad-23a22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDigFzCLtWOQxTBYci2bpcqod-_Srurgz0',
    appId: '1:841446464080:android:38e9243e504a4c55ba4f55',
    messagingSenderId: '841446464080',
    projectId: 'my-firebase-app-mad-23a22',
    storageBucket: 'my-firebase-app-mad-23a22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUN-gap6ov2LT1Ew3uPxcyuJ6jcspGd_8',
    appId: '1:841446464080:ios:3732af15cd14a4d8ba4f55',
    messagingSenderId: '841446464080',
    projectId: 'my-firebase-app-mad-23a22',
    storageBucket: 'my-firebase-app-mad-23a22.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );
}
